name: charts_tests
version: 0.12.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  charts:
    path: ../charts
  collection: ^1.14.5
  logging: ^1.0.2
  meta: ^1.1.1
  vector_math: ^2.0.8
  intl:
  equatable: ^2.0.5

dev_dependencies:
  mockito: ^5.0.0
  test: ^1.5.3
